Update ngen script to work with new hydro fabric
NOAA-OWP/t-route pull request #169
Opened 2020-11-18 22:33 UTC by donaldwj

[Short description explaining the high-level reason for the pull request]

## Additions

-

## Removals

-

## Changes

-

## Testing

1.

## Screenshots

## Notes

-

## Todos

-

## Checklist

- [ ] PR has an informative and human-readable title
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code can be automatically merged (no conflicts)
- [ ] Code follows project standards (link if applicable)
- [ ] Passes all existing automated tests
- [ ] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future todos are captured in comments
- [ ] Visually tested in supported browsers and devices (see checklist below :point_down:)
- [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [ ] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

## Testing checklist

### Target Environment support

- [ ] Windows
- [ ] Linux
- [ ] Browser

### Accessibility

- [ ] Keyboard friendly
- [ ] Screen reader friendly

### Other

- [ ] Is useable without CSS
- [ ] Is useable without JS
- [ ] Flexible from small to large screens
- [ ] No linting errors or warnings
- [ ] JavaScript tests are passing

2020-11-25 15:38 UTC, jdmattern-noaa requested changes
Looks good. Please also remove the four catchment output files (87, 88, 89, and 92) that are no longer being used because the code will read all catchment files in the directory.

2020-11-25 15:38 UTC, jdmattern-noaa commented on src/external_connections/next_gen_network.py
Please change the example usage on line 3 to include the new flowpath_data.geojson file instead and remove the previous geojson file from the repo.

2020-11-25 20:29 UTC, jdmattern-noaa approved these changes
Looks great. Thanks @donaldwj

2020-12-07 19:53 UTC, jameshalgren approved these changes

2020-12-07 19:54 UTC, merged

2020-12-07 20:07 UTC, jameshalgren commented
@donaldwj @jdmattern-noaa @hellkite500 
Squashed and merged this.