Write last obs to netcdf
NOAA-OWP/t-route pull request #458
Opened 2021-09-30 16:31 UTC by jhrehanoaa

I was testing this on Florence_test2_loop.yaml on Cheyenne. This picks up where the csv write out left off. I created a new branch as there was some rebasing and merging issues with the previous PR branch. Essentially, this makes the lastobs_df each run with these columns requesting (time,flow,nudge,etc.) then reads and writes out to nc. 

The current changes take place in main.py and the Florence_test2_loop.yaml files. Added a new yaml called Florence_test_lastobs_writeout.yaml on Cheyenne for simplicity.

2021-09-30 18:29 UTC, jameshalgren commented
Got this rebased with only relevant commits. @jhrehanoaa, please `git fetch && git checkout upstream/lastobssaved` and confirm prior testing.

2021-09-30 18:37 UTC, jameshalgren commented on src/nwm_routing/src/nwm_routing/__main__.py
> +                # lastobs_df = pd.read_csv(lastobs_string,index_col='link')
It seems like we are doing the same thing twice with the code block up top and this one here. Could they be consolidated?

2021-09-30 18:39 UTC, jameshalgren commented on src/nwm_routing/src/nwm_routing/__main__.py
> +            lastobs_df['gages'] = lastobs_df['gages'].astype(str).str.decode('utf-8')
This block, as an output function, is out of place up here in this part of the execution loop. I would suggest we make a function out of the block, then put it inside of the general output call here: https://github.com/NOAA-OWP/t-route/blob/b6cace768be819889d48e4bc99924208da1b3180/src/nwm_routing/src/nwm_routing/__main__.py#L1187

2021-09-30 18:40 UTC, jameshalgren commented on src/nwm_routing/src/nwm_routing/__main__.py
> +            lastobs_df['gages'] = lastobs_df['gages'].astype(str).str.decode('utf-8')
which... would remove the need for the xarray library in this main function.

2021-09-30 18:44 UTC, jameshalgren requested changes
We need to make this functionality available to all three execution modes. Right now it is attached to `main_v03` (i.e., "looping") execution. It needs also to be attached to the `main_v03_async` probably here: https://github.com/NOAA-OWP/t-route/blob/b6cace768be819889d48e4bc99924208da1b3180/src/nwm_routing/src/nwm_routing/__main__.py#L1481 and to the `main_v02` execution path, probably here: https://github.com/NOAA-OWP/t-route/blob/b6cace768be819889d48e4bc99924208da1b3180/src/nwm_routing/src/nwm_routing/__main__.py#L734

2021-09-30 21:06 UTC, jhrehanoaa commented
I made the requested changes. A good amount of information has to be passed to those output functions. I also fetched both the origin and my own, but it looks like it went ahead and added the commits again.

2021-10-01 19:02 UTC, jhrehanoaa commented
replaced by #460 to remove extra commits

2021-10-01 19:41 UTC, awlostowski-noaa commented
superseded by #460

2021-10-01 19:41 UTC, closed without merging