Check before performing CRS reprojection
NOAA-OWP/t-route pull request #686
Opened 2023-11-08 19:57 UTC by shorvath-noaa

t-route now checks if LAKEOUT files are too be created (set in yaml file under output_parameters -> lakeout_output:) before performing re-projection of waterbody_dataframe to get latitude, longitude, and crs information. 

This is an issue that arose due to sqlite3 versioning. This doesn't actually fix that problem, but is a workaround for now.

## Additions
AbstractNetwork.py
- add `output_parameters` slot

HYFeaturesNetwork.py
- Check if LAKEOUT files are to be created. If so, reproject geopandas.dataframe geometry column to get lat, lon, and crs columns
- If not creating LAKEOUT files, assign those columns np.nan
- Unrelated, but fix `pd.DataFrame.set_index()` error for `gage_df `

AbstractNetwork.py
- add `output_parameters` as input to `HYFeatures()`

## Removals

-

## Changes

-

## Testing

1.

## Screenshots

## Notes

-

## Todos

-

## Checklist

- [ ] PR has an informative and human-readable title
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code can be automatically merged (no conflicts)
- [ ] Code follows project standards (link if applicable)
- [ ] Passes all existing automated tests
- [ ] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future todos are captured in comments
- [ ] Visually tested in supported browsers and devices (see checklist below :point_down:)
- [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [ ] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

## Testing checklist

### Target Environment support

- [ ] Windows
- [ ] Linux
- [ ] Browser

### Accessibility

- [ ] Keyboard friendly
- [ ] Screen reader friendly

### Other

- [ ] Is useable without CSS
- [ ] Is useable without JS
- [ ] Flexible from small to large screens
- [ ] No linting errors or warnings
- [ ] JavaScript tests are passing

2023-11-08 20:06 UTC, hellkite500 requested changes

2023-11-08 20:06 UTC, hellkite500 commented on src/troute-network/troute/HYFeaturesNetwork.py
> +            import pdb; pdb.set_trace()
remove the debug trace

2023-11-08 20:08 UTC, shorvath-noaa commented on src/troute-network/troute/HYFeaturesNetwork.py
> +            import pdb; pdb.set_trace()
good catch, remvoed

2023-11-09 21:19 UTC, AminTorabi-NOAA approved these changes

2023-11-09 22:30 UTC, merged