Redone old PR 750 - empty lake DF
NOAA-OWP/t-route pull request #781
Opened 2024-06-10 23:27 UTC by JurgenZach-NOAA

[Short description explaining the high-level reason for the pull request]

## Additions

- Added provision when streamflow DA was turned on, but there were no lakes present - DA parameters are adjusted accordingly

## Removals

-

## Changes

-

## Testing

1.

## Screenshots

## Notes

-

## Todos

-

## Checklist

- [ ] PR has an informative and human-readable title
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code can be automatically merged (no conflicts)
- [ ] Code follows project standards (link if applicable)
- [ ] Passes all existing automated tests
- [ ] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future todos are captured in comments
- [ ] Visually tested in supported browsers and devices (see checklist below :point_down:)
- [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [ ] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

## Testing checklist

### Target Environment support

- [ ] Windows
- [ ] Linux
- [ ] Browser

### Accessibility

- [ ] Keyboard friendly
- [ ] Screen reader friendly

### Other

- [ ] Is useable without CSS
- [ ] Is useable without JS
- [ ] Flexible from small to large screens
- [ ] No linting errors or warnings
- [ ] JavaScript tests are passing

2024-06-18 14:46 UTC, shorvath-noaa requested changes

2024-06-18 14:46 UTC, shorvath-noaa commented on src/troute-network/troute/HYFeaturesNetwork.py
> +            self.data_assimilation_parameters['reservoir_da']['reservoir_rfc_da']['reservoir_rfc_forecasts']
need to add a `False` here?

2024-07-02 13:58 UTC, JurgenZach-NOAA reviewed
Applied requested fix

2024-07-02 15:00 UTC, shorvath-noaa approved these changes

2024-07-02 16:00 UTC, merged